version: '3.1'

services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 8080:8080

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./client:/usr/share/nginx/html/client
            - ./terminal:/usr/share/nginx/html/terminal
            - ./admin:/usr/share/nginx/html/admin
        ports:
            - 80:80

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: crbla
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306

volumes:
    db_data: